param(
    [Parameter(Mandatory = $true)]
    [string]$UnmatchedCsv,
    [Parameter(Mandatory = $true)]
    [string]$OutputSql
)

$ErrorActionPreference = 'Stop'
$rows = Import-Csv -Path $UnmatchedCsv
$splitRows = @($rows | Where-Object { $_.Ref -match '^\d+(?:/\d+)+$' })
$updates = New-Object System.Collections.Generic.List[string]
$invoiceOccurrences = New-Object System.Collections.Generic.List[object]

foreach ($row in $splitRows) {
    $tracking = $row.TrackingNumber -replace "'", "''"
    $podTime = ([datetime]::Parse($row.PodTimeLocal)).ToString("M/d/yyyy h:mm:ss tt", [System.Globalization.CultureInfo]::InvariantCulture)

    foreach ($invoice in ($row.Ref -split '/')) {
        $invoiceEscaped = $invoice -replace "'", "''"
        $invoiceOccurrences.Add([PSCustomObject]@{
            Invoice = $invoice
            Ref = $row.Ref
            Tracking = $row.TrackingNumber
        })

        $updates.Add(@"
UPDATE dbo.ArInvoice
SET PodReference = '$tracking',
    PodEntryDate = '$podTime',
    ProofOfDelivery = 'Y'
WHERE Invoice = REPLACE(SPACE(15 - LEN('$invoiceEscaped')) + '$invoiceEscaped', ' ', '0')
AND PodReference = ' ';
"@)
    }
}

$collisions = @($invoiceOccurrences | Group-Object Invoice | Where-Object Count -gt 1)
$header = @"
-- Generated by Generate-SplitInvoiceUpdates.ps1
-- Source CSV: $UnmatchedCsv
-- Split-reference rows: $($splitRows.Count)
-- Individual invoice updates: $($updates.Count)
-- Review before running against SYSPROCompanyE.
"@

if ($collisions.Count -gt 0) {
    $header += "-- WARNING: repeated invoice IDs are included below; the first update that finds PodReference = ' ' wins.`r`n"
    foreach ($collision in $collisions) {
        $details = $collision.Group | ForEach-Object { "$($_.Invoice) [$($_.Tracking)]" }
        $header += "-- Collision: $($details -join '; ')`r`n"
    }
}

($header + "`r`n" + ($updates -join "`r`n")) | Out-File -FilePath $OutputSql -Encoding utf8
Write-Host "Generated $($updates.Count) updates from $($splitRows.Count) split rows: $OutputSql"
if ($collisions.Count -gt 0) {
    Write-Warning "Found $($collisions.Count) repeated invoice IDs. Review the SQL header."
}
